import React from "react";
// import Blog2 from "../assets/images/Blog2.png";
import Blog2 from "../assets/image/Blog2.png";

const MarketingBlog = () => {
  return (
    <>
      <div className="max-w-3xl mx-auto my-10">
        {/* Banner Image */}
        <div className="relative">
          <img
            src={Blog2}
            alt="Marketing Blog"
            className="w-full rounded-lg shadow-md"
          />
          <div className="absolute top-2 right-2 bg-blue-400 text-white px-4 py-2 rounded-full text-sm flex items-center">
            13
          </div>
        </div>

        {/* Title */}
        <h2 className="text-2xl font-bold text-gray-800 text-center mt-4">
          Content Marketing: Exploring Diverse Content Formats
        </h2>

        {/* Meta Info */}
        <div className="text-center text-gray-600 mt-2">
          <span>27/12/2023</span> • <span>13 Min read</span>
        </div>

        {/* Blog Content */}
        <p className="text-gray-800 mt-4 text-start">
          “Triggering their pain points, agitating that pain, and finally
          solving their problems!” It sounds like gaslighting on purpose, but
          this is the gist of content marketing.Content marketing strategy
          consists of the creation and sharing of relevant materials to attract
          and engage the audience, establish expertise, promote brand awareness,
          and ultimately drive sales These strategies help to attract, engage,
          and retain an audience by creating and sharing relevant blogs, vlogs,
          or podcasts.
        </p>
        <p className="text-gray-800 mt-4 text-start">By establishing expertise through social campaigns,
          brands promote awareness and keep businesses at the top of the
          audience’s minds when it’s time to buy what they sell. According to
          statistics, 67% more leads are generated by blogs, with increased
          engagement being the prima facie evidence.
        </p>
        <p className="text-gray-800 mt-4 text-start"> How this works is
          interesting; blogs augment online visibility, generate leads, boost
          loyalty, and further drive improved authority.
        </p>

        {/* Subheading */}
        <h3 className="text-xl font-semibold mt-6 text-start">
          Types of Formats in Content Marketing

        </h3>

        {/* Paragraphs */}
        <p className="text-gray-800 mt-2 text-start">
          Content marketing is an umbrella term bifurcating into various modes of online, offline, and hybrid marketing techniques other than blogs, but first, let us understand blogs then we’ll move further:
        </p>
        {/* Subheading */}
        <h3 className="text-xl font-semibold mt-6 text-start">
          Blogs

        </h3>

        <p className="text-gray-800 mt-2 text-start">
          The cornerstone of building brand awareness and increasing engagement is Blogging. A blog, also known as a weblog, is a website that is updated regularly and can be used for commercial or personal comments. Blogs are frequently participatory, with comment boxes located at the foot of each post for readers to give their thoughts.
        </p>

        {/* Subheading */}
        <h3 className="text-xl font-semibold mt-6 text-start">
          Newsletter

        </h3>

        <p className="text-gray-800 mt-2 text-start">
          A newsletter is a bulletin issued periodically to the members of a society or other organization. The most widely known newsletter is the Zomato newsletter. Most of you must’ve read those quirky yet relatable emails from them. A newsletter is a regular email that contains a selection of your best articles, updates, and deals. Newsletters are used to increase brand exposure, traffic, and trust.
        </p>

        {/* Subheading */}
        <h3 className="text-xl font-semibold mt-6 text-start">
          Infographics
        </h3>

        <p className="text-gray-800 mt-2 text-start">
          The two key aspects of marketing are information and graphics; combine them and you get Infographics. According to Google, an infographic is a collection of imagery, data visualizations like pie charts and bar graphs, and minimal text that gives an easy-to-understand overview of a topic. Social media content agencies put all their creativity in marketing to gain a significantly larger audience.
        </p>
        \
        {/* Subheading */}
        <h3 className="text-xl font-semibold mt-6 text-start">
          Brochure
        </h3>

        <p className="text-gray-800 mt-2 text-start">
          A brochure is a corporate marketing instrument to promote a product or service. Both digitally and in print media, it can be created on one page or up to five pages. Guerrilla marketing is the most well-known application of this format, where companies distribute fictitious notes or wallets across the community; when people pick them up, they discover pamphlets inside. It became a case study of social media content strategy in a jiffy.
        </p>

        {/* Subheading */}
        <h3 className="text-xl font-semibold mt-6 text-start">
          Social Media
        </h3>

        <p className="text-gray-800 mt-2 text-start">
          With the world extending towards digitizing every possible aspect of life, marketing is also cybernated. As high-speed internet has become ubiquitous, social media marketing platforms have become a vital part of advertising, which helps brands reach out to a larger audience. In order to capture a multitude of audiences post excellent material on your social media pages, interact with and listen to your followers, evaluate your performance, and conduct social media ads. Some of the commonly known platforms are Instagram, Twitter now called X, Facebook etc
        </p>


        {/* Subheading */}
        <h3 className="text-xl font-semibold mt-6 text-start">
          Influencer Marketing
        </h3>

        <p className="text-gray-800 mt-2 text-start">
          Influencer Marketing
          An influencer is someone who can coax a sum of followers to act, utilize, and buy in a similar way as them using their social media content strategy. For doing this, they frequently receive compensation or free goods. Netflix is a fine paradigm of this, they invite influencers to make vlogs, podcasts, etc to cover launch events/parties of upcoming shows, films, and series. Some of the renowned influencers are Tanmay Bhat, Bani J, Isa Khan, Haley Kalil etc.
        </p>


        {/* Subheading */}
        <h3 className="text-xl font-semibold mt-6 text-start">
          Conclusion:
        </h3>

        <p className="text-gray-800 mt-2 text-start">
          Content marketing is much more comprehensive and enhanced than this but if you sum it all up, it comes down to
        </p>
        <p className="text-gray-800 mt-3 text-start">
          Establishing your foundation
        </p>
        <p className="text-gray-800 mt-3 text-start">
          Crafting compelling content
        </p>
        <p className="text-gray-800 mt-3 text-start">
          Implementing successful distribution strategies
        </p>
        <p className="text-gray-800 mt-3 text-start">
          Measuring success and adaptation.
        </p>
      </div>
    </>
  );
};

export default MarketingBlog;
